"""Kasaba layout and seeded residents. Independent of BuHouse."""

PLACES = [
    {
        "id": "iskele",
        "name": "İskele",
        "blurb": "Su kenarı. Oturanlar, gelen geçen, akşam ışığı.",
        "x": 52,
        "y": 11,
        "neighbors": ["park", "carsi"],
    },
    {
        "id": "park",
        "name": "Çınar Parkı",
        "blurb": "Banklar, köpekler, serin gölge.",
        "x": 20,
        "y": 28,
        "neighbors": ["iskele", "kutuphane", "carsi"],
    },
    {
        "id": "carsi",
        "name": "Çarşı",
        "blurb": "Kalabalık, dükkânlar, rastgele karşılaşmalar.",
        "x": 54,
        "y": 34,
        "neighbors": ["iskele", "park", "kafe", "durak"],
    },
    {
        "id": "kafe",
        "name": "Ada Kafe",
        "blurb": "Kahve, priz kavgası, yarı açık sohbetler.",
        "x": 82,
        "y": 30,
        "neighbors": ["carsi", "atolye", "cati"],
    },
    {
        "id": "kutuphane",
        "name": "Kütüphane",
        "blurb": "Kısık ses, masa paylaşımı, sınav haftası.",
        "x": 18,
        "y": 58,
        "neighbors": ["park", "durak"],
    },
    {
        "id": "durak",
        "name": "Durak",
        "blurb": "Beklemek. Kısa cümleler, ortak kader.",
        "x": 48,
        "y": 62,
        "neighbors": ["carsi", "kutuphane", "atolye"],
    },
    {
        "id": "atolye",
        "name": "Atölye",
        "blurb": "Uğraşanlar, müzik, açık kapı.",
        "x": 78,
        "y": 58,
        "neighbors": ["kafe", "durak", "cati"],
    },
    {
        "id": "cati",
        "name": "Çatı",
        "blurb": "Gece. Manzara, uzun konuşmalar.",
        "x": 70,
        "y": 82,
        "neighbors": ["kafe", "atolye"],
    },
]

NPCS = [
    {
        "name": "Deniz",
        "emoji": "🌊",
        "color": "#5ec2c7",
        "persona": "Meraklı, kitap okur, soru sorar, yumuşak konuşur.",
        "traits": "merakli,sakin,sosyal",
        "place_id": "kutuphane",
        "wander": 1,
    },
    {
        "name": "Mert",
        "emoji": "☕",
        "color": "#d4a574",
        "persona": "Esprili, kahve bağımlısı, kalabalıktan çekinmez.",
        "traits": "esprili,sosyal,gececi",
        "place_id": "kafe",
        "wander": 1,
    },
    {
        "name": "Ece",
        "emoji": "📷",
        "color": "#e08bb0",
        "persona": "Sakin, gözlemci, kısa ve net konuşur.",
        "traits": "sakin,kisa,merakli",
        "place_id": "park",
        "wander": 1,
    },
    {
        "name": "Baran",
        "emoji": "🎒",
        "color": "#7eb37a",
        "persona": "Yeni gelmiş, insan tanımak istiyor, biraz çekingen.",
        "traits": "yeni,sosyal,merakli",
        "place_id": "carsi",
        "wander": 1,
    },
    {
        "name": "Leyla",
        "emoji": "🌙",
        "color": "#9b8cff",
        "persona": "Gece kuşu, müzik konuşur, samimi ve uzun anlatır.",
        "traits": "gececi,sosyal,esprili",
        "place_id": "cati",
        "wander": 1,
    },
    {
        "name": "Can",
        "emoji": "🏃",
        "color": "#f0a05a",
        "persona": "Sabahçı, spor, pratik cümleler.",
        "traits": "kisa,sosyal,sakin",
        "place_id": "iskele",
        "wander": 1,
    },
    {
        "name": "Ayşe",
        "emoji": "📚",
        "color": "#c97b63",
        "persona": "Yüksek lisans, biraz yorgun, zekice ve dürüst.",
        "traits": "sakin,kisa,merakli",
        "place_id": "kutuphane",
        "wander": 1,
    },
    {
        "name": "Rüzgar",
        "emoji": "🗺️",
        "color": "#6aa6e8",
        "persona": "Her köşeyi sorar, turist gibi, heyecanlı.",
        "traits": "yeni,merakli,sosyal",
        "place_id": "iskele",
        "wander": 1,
    },
]

PLACE_BY_ID = {p["id"]: p for p in PLACES}
